### ISSUE TITLE
Please cleanup TradFriLibrary references

### ISSUE THREAD

**Issue by scheelings** [tomidix/CSharpTradFriLibrary#18]
Hi,
First of all, this is a great library, so thanks a lot!

I noticed that a lot of referenced assemblies exist in the TradFriLibrary project:
![image](https://user-images.githubusercontent.com/6839876/53954135-9562c280-40d5-11e9-9e3d-ca96bf420e70.png)
I have created a new project and copied all the source code from this library (and tested if everything still worked) and see the references which are actually needed:
![image](https://user-images.githubusercontent.com/6839876/53954282-1457fb00-40d6-11e9-80a6-f213c432a2c0.png)

Could you please cleanup your library?
Thx,
Danny

**Comment by davidwallis3101** [comment]
Create a branch make the changes and submit a pull request!

From: Danny Scheelings
Sent: 07 March 2019 11:40
To: tomidix/CSharpTradFriLibrary
Cc: Subscribed
Subject: [tomidix/CSharpTradFriLibrary] Please cleanup TradFriLibraryreferences (#18)

Hi,
First of all, this is a great library, so thanks a lot!
I noticed that a lot of referenced assemblies exist in the TradFriLibrary project:

I have created a new project and copied all the source code from this library (and tested if everything still worked) and see the references which are actually needed:

Could you please cleanup your library?
Thx,
Danny

**Comment by scheelings** [comment]
Pull request added: [https://github.com/tomidix/CSharpTradFriLibrary/pull/19](url)

**Comment by tomidix** [comment]
Thanks @scheelings .. I saw your pull request.

If you look at repo, we have a new feature branch which has many changes and improvements.
I'm currently working on an CI/CD procedure for it (nuget) because it is written in .netstandard which means that library will be available on both .net and dotnet core. 

I also have to decide weather we should just upgrade the nuget and continue working on this repo or we should have a new one for the .net standard. Anyway the plan is to support only one version of the library so basically it's just a question if there is any benefit to leave the current source code available to community. Existing Nuget packages definitely won't be deleted.

**Comment by scheelings** [comment]
Hi @tomidix,
I checked the feature branch and it works great. Better than the master branch code. So you can ignore my pull request.
I would make this feature branch the master branch, because it targets .Net standard so it is available on more platforms!

**Comment by tomidix** [comment]
New version is pushed to nuget (1.0.0.31) and it should be validated and available soon so I'm closing this issue.
